modLoader="javafml"
loaderVersion="[43,)"
license = "LGPL-3.0"
issueTrackerURL = "https://github.com/AbdElAziz333/Pluto/issues"
[[mods]]
modId = "pluto"
version = "${version}"
displayName = "Pluto"
#updateJSONURL = "https://github.com/AbdElAziz333/Pluto/raw/mc1.19.2/dev/updates.json"
displayURL = "https://www.curseforge.com/minecraft/mc-mods/pluto"
logoFile = "logo.png"
credits = "AbdElAziz, Tuxed"
authors = "AbdElAziz"
displayTest = "MATCH_VERSION"

description = '''
Pluto is a performance mod that optimizes Minecraft's networking stack and entity tracker.
'''

[[dependencies.pluto]]
modId="forge"
mandatory=true
versionRange="[43,)"
ordering="NONE"
side="BOTH"

[[dependencies.pluto]]
modId="minecraft"
mandatory = true
versionRange = "[1.19.2,)"
ordering = "NONE"
side="BOTH"